In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("VentasTransformed.csv", encoding="cp1252")
df.head()

,VentaID,FechaVenta,HoraVenta,SucursalNombre,VendedorNombre,ClienteNombre,GeneroCliente,EdadCliente,EmailCliente,TelefonoCliente,...,SubtotalProducto3,DescuentoVenta,TotalVenta,Año,Mes,Día,CiudadSucursal,MarcaProducto1,MarcaProducto2,MarcaProducto3
0,240,"martes, 7 de diciembre de 2021",11:28:42 p. m.,Techcore Medellín #2,Claudia Sastre-Quintero,Pánfilo Salazar,M,25,pánfilo11@yahoo.com,+34920 72 88 07,...,0,0.0,5200000,2021,12,7,Medellín,HP,No Aplica,No Aplica
1,637,"sábado, 15 de julio de 2017",11:02:30 p. m.,Techcore Medellín #1,Ana Sofía Llopis Blázquez,Crescencia Gutierrez Gimenez,F,18,crescencia98@hotmail.com,+34 883141900,...,0,0.0,5200000,2017,7,15,Medellín,HP,No Aplica,No Aplica
2,1096,"lunes, 27 de marzo de 2023",07:53:12 a. m.,Techcore Medellín #1,Eusebia Jara Macias,Cándido Pastor Plana,M,21,cándido49@gmail.com,+34943 846 175,...,0,0.0,5200000,2023,3,27,Medellín,HP,No Aplica,No Aplica
3,1249,"sábado, 16 de diciembre de 2023",04:51:13 p. m.,Techcore Medellín #2,Juan José Porcel-Riera,Goyo Garriga Jove,M,25,goyo24@gmail.com,+34921 23 07 32,...,0,0.0,5200000,2023,12,16,Medellín,HP,No Aplica,No Aplica
4,1346,"domingo, 27 de septiembre de 2015",10:06:21 a. m.,Techcore Medellín #1,Dominga del Alcántara,Florentino Ros Rovira,M,42,florentino54@hotmail.com,+34 900 23 11 50,...,0,0.0,5200000,2015,9,27,Medellín,HP,No Aplica,No Aplica

In [4]:
df.columns

Index(['VentaID', 'FechaVenta', 'HoraVenta', 'SucursalNombre',
       'VendedorNombre', 'ClienteNombre', 'GeneroCliente', 'EdadCliente',
       'EmailCliente', 'TelefonoCliente', 'DireccionCliente', 'MetodoPago',
       'NombreProducto1', 'CantidadProducto1', 'PrecioUnitarioProducto1',
       'SubtotalProducto1', 'NombreProducto2', 'CantidadProducto2',
       'PrecioUnitarioProducto2', 'SubtotalProducto2', 'NombreProducto3',
       'CantidadProducto3', 'PrecioUnitarioProducto3', 'SubtotalProducto3',
       'DescuentoVenta', 'TotalVenta', 'Año', 'Mes', 'Día', 'CiudadSucursal',
       'MarcaProducto1', 'MarcaProducto2', 'MarcaProducto3'],
      dtype='object')

In [5]:
df['FechaVenta'] = pd.to_datetime({
    'year': df['Año'],
    'month': df['Mes'],
    'day': df['Día']
})
df = df.rename(columns={'VentaID': 'FacturaID'})

## TABLA CIUDADES

In [6]:
ciudades= df['CiudadSucursal'].unique()
ciudades= pd.DataFrame(ciudades, columns=['Ciudad'])
ciudades['CiudadID'] = ciudades.index + 1
ciudades = ciudades[['Ciudad','CiudadID']]
ciudades.head()

     Ciudad  CiudadID
0  Medellín         1
1    Bogotá         2
2   Pereira         3
3      Cali         4

## TABLA SUCURSALES

In [7]:
sucursales = df[['SucursalNombre', 'CiudadSucursal']].drop_duplicates().reset_index(drop=True)
sucursales['SucursalID'] = sucursales.index + 1
sucursales = sucursales.merge(ciudades, left_on='CiudadSucursal', right_on='Ciudad', how='left')
sucursales = sucursales [['SucursalID','SucursalNombre','CiudadID']]
sucursales

   SucursalID        SucursalNombre  CiudadID
0           1  Techcore Medellín #2         1
1           2  Techcore Medellín #1         1
2           3    Techcore Bogotá #1         2
3           4    Techcore Bogotá #2         2
4           5      Techcore Pereira         3
5           6         Techcore Cali         4

## TABLA VENDEDORES

In [8]:
vendedores = df['VendedorNombre'].unique()
vendedores = pd.DataFrame(vendedores, columns=['VendedorNombre'])
vendedores ['VendedorID'] = vendedores.index +1
vendedores = vendedores[['VendedorID','VendedorNombre']]

vendedores

    VendedorID                   VendedorNombre
0            1          Claudia Sastre-Quintero
1            2        Ana Sofía Llopis Blázquez
2            3              Eusebia Jara Macias
3            4           Juan José Porcel-Riera
4            5            Dominga del Alcántara
5            6           Liliana Jordá Armengol
6            7                     Juanito Diaz
7            8                     Luisina Lasa
8            9  Almudena Adelaida Lledó Garrido
9           10               Ibán López Córdoba
10          11        Poncio Gabriel Poza Acedo
11          12         Herminia Meléndez-Huguet
12          13            Evaristo Guillen Peña
13          14           Carina Parejo Carranza
14          15                 Edu Juan Pedraza
15          16        Florencio Iker Vara Nebot
16          17           Basilio Marcos Barrena
17          18             Eloísa Plaza Hurtado
18          19        María Belén Alegria Camps
19          20          Rosendo Barberá Cordero
20          21         Clímaco Salinas Zabaleta
21          22          Griselda Arnaiz Palacio
22          23         Jose Angel Rovira Adadia
23          24             Jacinta Juárez Marín
24          25                María Ramírez Pou
25          26              Armida Azorin Plaza
26          27           Amílcar Ortega-Alberto
27          28                Aura del Bermúdez
28          29               Olivia Armas Ayuso
29          30          Anacleto Morera Segovia

## TABLA CLIENTES

In [9]:
Clientes = df[['ClienteNombre','GeneroCliente','EdadCliente','EmailCliente',
               'TelefonoCliente','DireccionCliente']].drop_duplicates().reset_index(drop=True)
Clientes['ClienteID'] = Clientes.index +1
Clientes = Clientes[['ClienteID','ClienteNombre','GeneroCliente','EdadCliente','EmailCliente',
               'TelefonoCliente','DireccionCliente']]


Clientes.head()

,ClienteID,ClienteNombre,GeneroCliente,EdadCliente,EmailCliente,TelefonoCliente,DireccionCliente
0,1,Pánfilo Salazar,M,25,pánfilo11@yahoo.com,+34920 72 88 07,cra 55 #46-70
1,2,Crescencia Gutierrez Gimenez,F,18,crescencia98@hotmail.com,+34 883141900,cra 60 #66-27
2,3,Cándido Pastor Plana,M,21,cándido49@gmail.com,+34943 846 175,cll 33 #11-22
3,4,Goyo Garriga Jove,M,25,goyo24@gmail.com,+34921 23 07 32,cll 21 #97-27
4,5,Florentino Ros Rovira,M,42,florentino54@hotmail.com,+34 900 23 11 50,cll 14 #76-41

## TABLA DE MÉTODOS DE PAGO

In [10]:
MetodosPago = df['MetodoPago'].unique()
MetodosPago = pd.DataFrame(MetodosPago, columns=['MetodoPago'])
MetodosPago['MetodoPagoID'] = MetodosPago.index +1
MetodosPago = MetodosPago[['MetodoPago','MetodoPagoID']]



MetodosPago

          MetodoPago  MetodoPagoID
0    Tarjeta Crédito             1
1     Tarjeta Débito             2
2      Transferencia             3
3           Efectivo             4
4  Billetera Digital             5
5    No Especificado             6

## TABLA FACTURAS

In [11]:
Facturas = df[['FacturaID','FechaVenta','HoraVenta','SucursalNombre','VendedorNombre',
               'ClienteNombre','EmailCliente','MetodoPago','DescuentoVenta','TotalVenta']]
Facturas = Facturas.merge(sucursales, left_on='SucursalNombre' , right_on='SucursalNombre', how= 'left')
Facturas = Facturas.merge(vendedores, left_on='VendedorNombre' , right_on='VendedorNombre', how= 'left')
Facturas = Facturas.merge(Clientes, left_on=['ClienteNombre','EmailCliente'] , right_on=['ClienteNombre','EmailCliente'], how= 'left')
Facturas = Facturas.merge(MetodosPago, left_on='MetodoPago' , right_on='MetodoPago', how= 'left')
Facturas = Facturas[['FacturaID','FechaVenta','HoraVenta','SucursalID','VendedorID',
                     'ClienteID','MetodoPagoID','DescuentoVenta','TotalVenta']]


Facturas.head(20)

,FacturaID,FechaVenta,HoraVenta,SucursalID,VendedorID,ClienteID,MetodoPagoID,DescuentoVenta,TotalVenta
0,240,2021-12-07,11:28:42 p. m.,1,1,1,1,0.0,5200000
1,637,2017-07-15,11:02:30 p. m.,2,2,2,1,0.0,5200000
2,1096,2023-03-27,07:53:12 a. m.,2,3,3,1,0.0,5200000
3,1249,2023-12-16,04:51:13 p. m.,1,4,4,1,0.0,5200000
4,1346,2015-09-27,10:06:21 a. m.,2,5,5,1,0.0,5200000
5,1777,2015-09-03,08:30:12 a. m.,1,4,6,1,0.0,5200000
6,2188,2020-05-12,09:17:28 p. m.,2,6,7,1,0.0,5200000
7,2424,2022-02-15,12:21:19 p. m.,1,7,8,1,0.0,5200000
8,2655,2022-08-14,06:19:56 p. m.,2,2,9,1,0.0,5200000
9,2755,2016-03-17,03:16:17 p. m.,2,3,10,1,0.0,5200000
10,3700,2021-04-29,11:51:26 p. m.,2,5,11,1,0.0,5200000
11,3985,2024-07-31,02:18:32 p. m.,2,5,12,1,0.0,5200000
12,4875,2024-09-05,07:44:06 a. m.,2,6,13,1,0.0,5200000
13,5847,2023-10-13,08:13:38 p. m.,2,3,14,1,0.0,5200000
14,6723,2021-07-22,11:57:43 a. m.,1,4,15,1,0.0,5200000
15,7005,2023-10-07,05:29:22 a. m.,1,8,16,1,0.0,5200000
16,7737,2019-03-29,07:01:43 a. m.,1,1,17,1,0.0,5200000
17,7740,2022-12-12,11:03:10 a. m.,1,1,18,1,0.0,5200000
18,8161,2016-10-19,01:01:25 a. m.,2,5,19,1,0.0,5200000
19,8250,2016-10-18,11:09:30 p. m.,2,3,20,1,0.0,5200000

In [12]:
print(Facturas[Facturas['DescuentoVenta'] > 0]['DescuentoVenta'].unique())

[0.05 0.1  0.15]

## TABLA DE PRODUCTOS

In [13]:
Productos = pd.DataFrame(columns=['NombreProducto','MarcaProducto','Precio'])
for x in range(1,4):
    append_producto = pd.DataFrame(columns=['NombreProducto','MarcaProducto','Precio'])
    append_producto ['NombreProducto'] = df[f'NombreProducto{x}']
    append_producto ['MarcaProducto']  = df[f'MarcaProducto{x}']
    append_producto ['Precio']         = df[f'PrecioUnitarioProducto{x}']
    Productos = pd.concat([Productos,append_producto],ignore_index=True)
    
Productos = Productos.dropna().drop_duplicates().reset_index(drop=True)
Productos  ['ProductoID'] = Productos.index + 1
Productos = Productos[['ProductoID','NombreProducto','MarcaProducto','Precio']]

Productos.head()

   ProductoID   NombreProducto MarcaProducto   Precio
0           1  HP Spectre x360            HP  5200000
1           2       HP Omen 16            HP  6000000
2           3   HP Pavilion 15            HP  3500000
3           4       HP Envy 13            HP  4000000
4           5   Lenovo Yoga 7i        Lenovo  4400000

## TABLA DETALLE FACTURAS

In [14]:
lista_detalles = []

for i in range(1, 4):
    detalle_temp = df[['FacturaID', f'NombreProducto{i}', f'MarcaProducto{i}', f'CantidadProducto{i}']].copy()
    detalle_temp = detalle_temp.merge(
        Productos,
        left_on=[f'NombreProducto{i}', f'MarcaProducto{i}'],
        right_on=['NombreProducto', 'MarcaProducto'],
        how='left'
    )
    detalle_temp = detalle_temp[['FacturaID', 'ProductoID', f'CantidadProducto{i}']].rename(columns={f'CantidadProducto{i}': 'Cantidad'})
    lista_detalles.append(detalle_temp)

DetalleFacturas = pd.concat(lista_detalles, ignore_index=True)
DetalleFacturas = DetalleFacturas.dropna()
DetalleFacturas = DetalleFacturas[DetalleFacturas['Cantidad'] > 0]
DetalleFacturas['FacturaID'] = DetalleFacturas['FacturaID'].astype(int)
DetalleFacturas['ProductoID'] = DetalleFacturas['ProductoID'].astype(int)
DetalleFacturas['Cantidad'] = DetalleFacturas['Cantidad'].astype(int)
DetalleFacturas = DetalleFacturas.sort_values(by=['FacturaID']).reset_index(drop=True)
DetalleFacturas.insert(0, 'DetalleID', DetalleFacturas.index + 1)

print(DetalleFacturas['FacturaID'].unique()[:10])
DetalleFacturas.head(5)

[ 1  2  3  4  5  6  7  8  9 10]

   DetalleID  FacturaID  ProductoID  Cantidad
0          1          1           9         1
1          2          1          13         1
2          3          1          35         2
3          4          2          24         1
4          5          2           8         1

## HUERFANOS

In [12]:
h1 = DetalleFacturas[~DetalleFacturas['FacturaID'].isin(Facturas['FacturaID'])]
print(f'FacturaIDs      huérfanos en DetalleFacturas: {len(h1)}')
h2 = DetalleFacturas[~DetalleFacturas['ProductoID'].isin(Productos['ProductoID'])]
print(f'ProductoIDs     huérfanos en DetalleFacturas: {len(h2)}')
h3 = Facturas[~Facturas['SucursalID'].isin(sucursales['SucursalID'])]
print(f'SucursalIDs     huérfanos en DetalleFacturas: {len(h3)}')
h4 = Facturas[~Facturas['VendedorID'].isin(vendedores['VendedorID'])]
print(f'VendedorIDs     huérfanos en DetalleFacturas: {len(h4)}')
h5 = Facturas[~Facturas['ClienteID'].isin(Clientes['ClienteID'])]
print(f'ClienteIDs      huérfanos en DetalleFacturas: {len(h5)}')
h6 = Facturas[~Facturas['MetodoPagoID'].isin(MetodosPago['MetodoPagoID'])]
print(f'MetodoPagoIDs   huérfanos en DetalleFacturas: {len(h6)}')
h7 = sucursales[~sucursales['CiudadID'].isin(sucursales['CiudadID'])]
print(f'CiudadIDs       huérfanos en DetalleFacturas: {len(h7)}')

FacturaIDs      huérfanos en DetalleFacturas: 0
ProductoIDs     huérfanos en DetalleFacturas: 0
SucursalIDs     huérfanos en DetalleFacturas: 0
VendedorIDs     huérfanos en DetalleFacturas: 0
ClienteIDs      huérfanos en DetalleFacturas: 0
MetodoPagoIDs   huérfanos en DetalleFacturas: 0
CiudadIDs       huérfanos en DetalleFacturas: 0

In [13]:
VentasMarca = DetalleFacturas.merge(Productos, on='ProductoID')[['MarcaProducto','Subtotal']].groupby('MarcaProducto').sum().sort_values('Subtotal',ascending=False)
pd.options.display.float_format = '{:,.0f}'.format
print(VentasMarca)

                     Subtotal
MarcaProducto
Lenovo        117,879,200,000
HP             96,786,700,000
Dell           86,722,000,000
Apple          78,016,200,000
Asus           33,179,600,000
Acer           22,000,400,000
Samsung        12,760,800,000
MSI             8,525,200,000
Microsoft       8,223,400,000
Razer           3,936,400,000

In [14]:
TopVentas = DetalleFacturas.merge(Productos, on='ProductoID')[['NombreProducto','Cantidad']].groupby('NombreProducto').sum().sort_values('Cantidad',ascending=False).head(10)
pd.options.display.float_format = '{:,.0f}'.format
TopVentas

                           Cantidad
NombreProducto
HP Spectre x360                7726
Lenovo Legion 5 Pro            5861
Lenovo ThinkPad X1 Carbon      5814
Lenovo Yoga 7i                 5052
HP Omen 16                     5011
Lenovo IdeaPad 5               4970
Dell XPS 13                    4526
Dell Latitude 7420             4507
HP Pavilion 15                 4029
Dell Alienware m15             3658

In [34]:
print(Facturas['DescuentoVenta'].apply(lambda x: str(x)).unique())

['0.0' '0.05' '0.1' '0.15']

In [38]:
with pd.ExcelWriter('modeloVentas.xlsx', engine='openpyxl') as writer:
    Facturas.to_excel(writer, sheet_name='Facturas', index=False)
    DetalleFacturas.to_excel(writer, sheet_name='DetalleFacturas', index=False)
    Productos.to_excel(writer, sheet_name='Productos', index=False)
    Clientes.to_excel(writer, sheet_name='Clientes', index=False)
    sucursales.to_excel(writer, sheet_name='Sucursales', index=False)
    ciudades.to_excel(writer, sheet_name='Ciudades', index=False)
    vendedores.to_excel(writer, sheet_name='Vendedores', index=False)
    MetodosPago.to_excel(writer, sheet_name='MetodosPago', index=False)

In [15]:
df = pd.read_csv("VentasTransformed.csv", encoding="cp1252")
df = df.rename(columns={'VentaID': 'FacturaID'})
df['FacturaID'] = df['FacturaID'].astype(int)
print(df['FacturaID'].unique()[:5])  # verificar

[ 240  637 1096 1249 1346]

In [16]:
test = df[['FacturaID', 'NombreProducto1', 'MarcaProducto1', 'CantidadProducto1']].copy()
resultado = pd.concat([test, test], ignore_index=True)
print(resultado['FacturaID'].unique()[:5])

[ 240  637 1096 1249 1346]

In [17]:
print(DetalleFacturas['FacturaID'].unique()[:10])

[ 1  2  3  4  5  6  7  8  9 10]